version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  app:
    build: .
    container_name: node-app
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/mydb
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
